version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ros_net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - ros2api
    networks:
      - ros_net

  ros2api:
    build: ./ros2api
    ports:
      - "8000:8000"
    networks:
      - ros_net
    environment:
      - ROS_DOMAIN_ID=0

networks:
  ros_net:
    external: true
